set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
set langmenu=zh_CN.utf-8
set imcmdline

syntax on
set nu
set autoindent
set smartindent
set mouse=a
set backspace=2
set tabstop=4
set softtabstop=4
set expandtab
set shiftwidth=4
set cursorline
highlight CursorLine ctermbg=darkblue ctermfg=grey cterm=bold
set colorcolumn=130
highlight ColorColumn ctermbg=green
"set cursorcolumn
"set showcmd
"set cmdheight=2
set hlsearch
set ignorecase
set history=1024
set wrap
set showmatch
set autoread
"set粘贴模式，这样粘贴过来的程序代码就不会错位了
"set paste

"display TAB key
set list
set listchars=tab:>-,trail:-,extends:>,precedes:<

set fileformats=unix
set laststatus=2

"set statusline=%<%F%h%m%r%h%w%y\ %{}&ff}\ %{}strftime()\""%d/%m/%y\ -\ %H:%M\"")}%=\ ascii:%b\ lin:%l\,%L\ %P
set statusline=[%F]%h%y%r%w%m%*%=%=\ ascii:%b\ Line:[%l/%L],Column:[%c][%p%%]
highlight StatusLine cterm=bold ctermfg=yellow ctermbg=blue
set ruler

"set for vbundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'

"original repos on git hub
Bundle 'kien/ctrlp.vim'
Bundle 'sukima/xmledit'
Bundle 'jiangmiao/auto-pairs'
Bundle 'klen.python-mode'
Bundle 'Valloric/ListToggle'
Bundle 'EasyGrep'
Bundle 'ShowPairs'
Bundle 'SudoEdit.vim'
Bundle 'Yggdroot/indentLine'

filetype on
filetype plugin on
filetype plugin indent on


"Taglist
"find . | grep -E -i ''\.c$|\.h$|\.s$|\.cpp$|\.cxx$|\.cc$|\.java$|\.hh$|\.lds$'' > cscope.files
nnoremap tl :Tlist<ENTER>
"map <silent> <F4> :TlistToggle<cr>
let Tlist_Exit_OnlyWindow=1
"let Tlist_Use_Right_Window=1
let Tlist_File_Fold_Auto_Close=1

"indenLine
let g:indentLine_enabled = 1
let g:indentLine_char = '¦'
let g:indentLine_color_term = 50

inoremap ( ()<ESC>i
inoremap [ []<ESC>i
inoremap { {}<ESC>i
inoremap < <><ESC>i
inoremap " ""<ESC>i
inoremap ' ''<ESC>i

inoremap jk <ESC>

nnoremap <F2> <C-W>w
nnoremap <F12> :q!<ENTER>

nnoremap <Space> %
vnoremap <Space> %

nnoremap ma :set mouse=a<CR>
nnoremap m<Space> :set mouse=<CR>
